services:
  backend:
    container_name: serverless-lab
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    working_dir: /app
    command: sleep infinity
    stop_grace_period: 2s
